export type NodeType =
  | "Program"
  | "ExpressionStatement"
  | "BinaryExpression"
  | "AssignmentExpression"
  | "ArrowFunctionExpression"
  | "NumericLiteral"
  | "VariableDeclaration"
  | "VariableDeclarator"
  | "FunctionDeclaration"
  | "CallExpression"
